import React from "react";
import {AbsoluteFill, Img, interpolate, staticFile, useCurrentFrame, useVideoConfig} from "remotion";
import {FONT_FAMILY, bezier, clamped, revealStyle, springProgress} from "../helpers";
import {MOTION} from "../tokens";

// =============================================================================
// Scene 08 — segment_007 — "Pull the data / dashboard performance trend"
//
// Source: 60 frames @ 25fps. Recreated as 180 frames @ 30fps.
// Source N -> Remotion ~ 3*(N-1). Scene starts at Remotion 1082.
//
// Beat map (local Remotion frames inside the 180-frame scene):
//   0..21    carry-over: Ads Manager grid + prompt card; typing finishes
//            ("Pull the data" -> full sentence) over frames 0..21
//   12..30   ads-manager grid fades out (just prompt card remains)
//   21..42   cursor approaches send button
//   42..54   hold (cursor sits on send button)
//   52..60   button click + wash to paper white
//   60..81   "Ads insights performance trend" serif title wipes L->R
//   81..96   stat cards stagger in (Spend, Purchases, CPA, ROAS)
//   93..132  blue Spend curve draws left-to-right
//   132..180 green dotted Purchases curve draws left-to-right
// =============================================================================

const PAPER = "#F6F4EE";          // soft off-white paper bg (lighter)
const PAPER_PROMPT = "#F4F2EC";   // slightly cooler under-tone behind prompt
const INK = "#1A1A1A";            // primary text
const INK_SOFT = "#8A8680";       // muted secondary
const BURNT = "#C0533B";          // send button red/orange
const PEACH = "#DFA99F";          // freshly-typed peach accent (muted)
const CARD_BORDER = "#E8E4DA";
const FB_BLUE = "#1877F2";
const CHART_BLUE = "#3B82F6";
const CHART_GREEN = "#22C55E";
const GREEN_DELTA = "#1FB55C";
const RED_DELTA = "#E14C4C";
const GRID_LINE = "#F0EDE3";

// 8 background ad-creative tiles (generated by gen_scene08.py).
const TILES = [
  "/aigen/scene08/t1_cozy_pouch.png",
  "/aigen/scene08/t2_bluetop_creator.png",
  "/aigen/scene08/t3_dog_pouch.png",
  "/aigen/scene08/t4_carseat_pouch.png",
  "/aigen/scene08/t5_kitchen_review.png",
  "/aigen/scene08/t6_shelf_browse.png",
  "/aigen/scene08/t7_picnic_pouch.png",
  "/aigen/scene08/t8_desk_overhead.png",
];

// Full prompt text. By scene start, the user has already typed "Pull the data".
const PROMPT_TEXT =
  "Pull the data on all 20 videos, understand why the top 5 worked, and based on that generate 10 more videos";
const PREFIX_LEN = "Pull the data".length;

// Title (post-wash hero, serif).
const HERO_TITLE = "Ads insights performance trend";

// ──────────────────────────────────────────────────────────────────────────────
// Sub-components
// ──────────────────────────────────────────────────────────────────────────────

const SendArrow: React.FC<{size: number}> = ({size}) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    style={{display: "block"}}
  >
    <path
      d="M12 19V5M12 5L6 11M12 5L18 11"
      stroke="#fff"
      strokeWidth={2.6}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

// Cartoon pointing-hand cursor (matches scene 04).
const HandCursor: React.FC<{size: number}> = ({size}) => (
  <svg
    width={size}
    height={size * 1.1}
    viewBox="0 0 100 110"
    style={{display: "block", filter: "drop-shadow(0 1px 1px rgba(0,0,0,0.25))"}}
  >
    <path
      d="M44 8 C44 4, 56 4, 56 8 L56 48 L66 48 C72 48, 76 52, 76 58 L76 82 C76 96, 64 104, 50 104 C36 104, 24 96, 24 82 L24 60 C24 56, 28 54, 32 56 L36 58 L36 14 C36 10, 44 10, 44 14 Z"
      fill="#fff"
      stroke="#111"
      strokeWidth={2.6}
      strokeLinejoin="round"
    />
    <path d="M40 78 L52 78 M40 86 L52 86 M40 94 L52 94" stroke="#111" strokeWidth={2.2} strokeLinecap="round"/>
  </svg>
);

const FacebookLogo: React.FC<{size: number}> = ({size}) => (
  <svg width={size} height={size} viewBox="0 0 32 32" style={{display: "block"}}>
    <circle cx={16} cy={16} r={16} fill={FB_BLUE}/>
    <path
      d="M18.4 16.6h2.1l.32-2.66h-2.42v-1.7c0-.77.21-1.3 1.3-1.3h1.4V8.55c-.24-.03-1.07-.1-2.05-.1-2.03 0-3.42 1.24-3.42 3.52v1.97h-2.3v2.66h2.3V23.4h2.77v-6.8z"
      fill="#fff"
    />
  </svg>
);

const StackIcon: React.FC<{size: number}> = ({size}) => (
  <svg width={size} height={size} viewBox="0 0 32 32" style={{display: "block"}}>
    <rect x={8} y={8} width={14} height={14} rx={2.5} stroke={FB_BLUE} strokeWidth={2.5} fill="none"/>
    <rect x={12} y={12} width={14} height={14} rx={2.5} stroke={FB_BLUE} strokeWidth={2.5} fill="#fff"/>
  </svg>
);

// Stat card.
const StatCard: React.FC<{
  label: string;
  value: string;
  delta: string;
  deltaPositive: boolean;
}> = ({label, value, delta, deltaPositive}) => {
  const arrow = deltaPositive ? "↑" : "↓";
  const col = deltaPositive ? GREEN_DELTA : GREEN_DELTA; // source shows green for both up and down
  return (
    <div
      style={{
        flex: 1,
        background: "#fff",
        border: `1px solid ${CARD_BORDER}`,
        borderRadius: 18,
        padding: "26px 32px 28px",
        boxShadow: "0 1px 2px rgba(0,0,0,0.025)",
      }}
    >
      <div style={{fontSize: 26, color: INK_SOFT, fontWeight: 500, letterSpacing: -0.1}}>
        {label}
      </div>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 18,
          marginTop: 10,
        }}
      >
        <div style={{fontSize: 76, fontWeight: 650, color: INK, letterSpacing: -2.0, lineHeight: 1}}>
          {value}
        </div>
        <div style={{fontSize: 26, color: col, fontWeight: 500, marginTop: 4}}>
          {arrow}{delta}
        </div>
      </div>
    </div>
  );
};

// ──────────────────────────────────────────────────────────────────────────────
// Chart helpers — deterministic data + smooth path
// ──────────────────────────────────────────────────────────────────────────────

// ──────────────────────────────────────────────────────────────────────────────
// Chart series — hand-picked control points roughly tracing the source
// Spend/Purchases curves: small zigzag on the left, dip mid, surge right.
// Values are in axis units (Spend $60..$260 ; Purchases 2..16).
// ──────────────────────────────────────────────────────────────────────────────
const SPEND_POINTS: number[] = [
  70, 90, 75, 82, 100, 78, 100, 130, 122, 112, 130, 105, 92, 100, 145, 175, 168,
  155, 175, 180, 162, 195, 215, 195, 210, 218, 200, 215, 230, 238, 248,
];
const PURCH_POINTS: number[] = [
  2.5, 3.5, 2.8, 3.2, 4.2, 3.0, 3.8, 5.4, 5.0, 4.6, 5.4, 4.3, 3.8, 3.9, 6.0,
  7.4, 7.0, 6.5, 7.2, 7.6, 6.4, 8.4, 9.6, 9.4, 10.6, 11.0, 11.5, 12.4, 13.0,
  13.8, 14.6,
];

// Convert series + draw progress to a Catmull-Rom smoothed SVG path.
const smoothPath = (
  pts: Array<{x: number; y: number}>,
  visibleCount: number
): string => {
  if (visibleCount <= 0 || pts.length === 0) return "";
  const n = Math.min(visibleCount, pts.length);
  const visible = pts.slice(0, n);
  if (visible.length === 1) {
    return `M ${visible[0].x} ${visible[0].y}`;
  }
  // Cardinal spline (k=0.5 ~ Catmull-Rom) to cubic beziers.
  let d = `M ${visible[0].x} ${visible[0].y}`;
  for (let i = 0; i < visible.length - 1; i++) {
    const p0 = visible[Math.max(0, i - 1)];
    const p1 = visible[i];
    const p2 = visible[i + 1];
    const p3 = visible[Math.min(visible.length - 1, i + 2)];
    const c1x = p1.x + (p2.x - p0.x) / 6;
    const c1y = p1.y + (p2.y - p0.y) / 6;
    const c2x = p2.x - (p3.x - p1.x) / 6;
    const c2y = p2.y - (p3.y - p1.y) / 6;
    d += ` C ${c1x} ${c1y} ${c2x} ${c2y} ${p2.x} ${p2.y}`;
  }
  return d;
};

// ──────────────────────────────────────────────────────────────────────────────
// Scene
// ──────────────────────────────────────────────────────────────────────────────
export const Scene08Seg007: React.FC = () => {
  const frame = useCurrentFrame();
  const {fps} = useVideoConfig();

  // ===== Beat 1 — carry-over Ads Manager + prompt typing (0..54) =====

  // Typing: by scene start, "Pull the data" is already typed. Continue typing
  // through local frame ~21 (src 8).
  const totalChars = PROMPT_TEXT.length;
  const typingChars = Math.max(
    PREFIX_LEN,
    Math.min(
      totalChars,
      Math.floor(interpolate(frame, [0, 30], [PREFIX_LEN + 1, totalChars], clamped))
    )
  );
  const typed = PROMPT_TEXT.slice(0, typingChars);
  // Peach-tinted tail: last ~5 chars of currently-typed string, fades to ink.
  const tailLen = 5;
  const tailStart = Math.max(0, typed.length - tailLen);
  const typedHead = typed.slice(0, tailStart);
  const typedTail = typed.slice(tailStart);
  // Tail fades to ink after typing completes.
  const tailColorMix = interpolate(frame, [21, 32], [0, 1], clamped);
  const tailColor = blendHex(PEACH, INK, tailColorMix);

  // Cursor: enters from below-right, hovers near send button.
  const cursorVis = interpolate(frame, [18, 30], [0, 1], clamped);
  const cursorDX = interpolate(frame, [18, 42], [120, 0], {
    ...clamped,
    easing: bezier(MOTION.expoOut),
  });
  const cursorDY = interpolate(frame, [18, 42], [140, 0], {
    ...clamped,
    easing: bezier(MOTION.expoOut),
  });

  // Button click around local frame 54 (source f19 ~= 54).
  const buttonClick = interpolate(frame, [52, 56, 62], [1, 0.92, 1], clamped);

  // ===== Beat 2 — wash to paper (52..60) — quick wash =====
  const whiteWash = interpolate(frame, [52, 60], [0, 1], clamped);

  // ===== Beat 3 — hero serif title (60..84) =====
  // Wipe in left-to-right via clip-path. Use a near-linear curve so the
  // sweep is visually progressive (expoOut would snap to ~100% too early).
  const titleVis = interpolate(frame, [60, 66], [0, 1], clamped);
  const titleSweep = interpolate(frame, [60, 84], [0, 100], clamped);

  // ===== Beat 4 — stat cards stagger (81..102) =====
  const statDelays = [81, 84, 87, 90];
  const statStyles = statDelays.map((d) => revealStyle(frame, fps, d, 22, 0.99));
  // No counter — show final values once card fades in (per Gemini feedback).
  const spendVal = "$4.8K";
  const purchVal = "218";
  const cpaVal = "$22.00";
  const roasVal = "3.4x";

  // ===== Beat 5 — chart (93..180) =====
  const chartIntro = springProgress(frame, fps, 93, 18, MOTION.smooth);
  const chartOpacity = chartIntro;
  const blueSeries = SPEND_POINTS;
  const greenSeries = PURCH_POINTS;
  const blueProg = interpolate(frame, [93, 138], [0, 1], clamped);
  const greenProg = interpolate(frame, [122, 168], [0, 1], clamped);

  // ===== Layout constants =====
  const W = 1920;
  const H = 1080;

  // ── Background Ads Manager scaffold (fades out early, well before wash) ──
  // Source: bg-grid + ads-manager chrome fully fade by ~src f12 (local 33).
  const bgOpacity = interpolate(frame, [21, 33], [1, 0], clamped);
  // Prompt card stays visible longer (until the wash hits).
  const cardOpacity = interpolate(whiteWash, [0, 1], [1, 0], clamped);

  // Grid geometry: 5 cols, 3 rows of vertical 9:16 tiles. The first row peeks
  // above the prompt card, the next rows continue below it. Source f001 shows
  // ads-manager header at top-left, then a row of tiles, then prompt card,
  // then another partial row below.
  const gridLeft = 380;
  const gridTop = 150;
  const tileW = 222;
  const tileH = 360;
  const tileGapX = 28;
  const tileGapY = 26;
  // Faint paper wash that sits between the bg-grid and the prompt card.
  const bgWashOpacity = 0.74;

  // Prompt card geometry.
  const promptCardW = 1760;
  const promptCardX = (W - promptCardW) / 2;
  const promptCardY = 410;

  return (
    <AbsoluteFill style={{background: PAPER, fontFamily: FONT_FAMILY, color: INK}}>
      {/* ───── Background: Ads Manager mock (beat 1) ───── */}
      <div style={{position: "absolute", inset: 0, opacity: bgOpacity}}>
        {/* Header chrome: Facebook logo + Ads Manager wordmark */}
        <div
          style={{
            position: "absolute",
            top: 56,
            left: 400,
            display: "flex",
            alignItems: "center",
            gap: 24,
          }}
        >
          <FacebookLogo size={60} />
          <div
            style={{
              fontSize: 60,
              fontWeight: 500,
              color: INK_SOFT,
              letterSpacing: -1.2,
            }}
          >
            Ads Manager
          </div>
        </div>
        {/* Stack icon below */}
        <div
          style={{
            position: "absolute",
            top: 222,
            left: 400,
          }}
        >
          <StackIcon size={56} />
        </div>

        {/* 5 x 3 grid of UGC ad-creative tiles. Render middle 3 rows (rows
            spill below the card, top row above the card). */}
        <div
          style={{
            position: "absolute",
            top: gridTop,
            left: gridLeft,
            display: "grid",
            gridTemplateColumns: `repeat(5, ${tileW}px)`,
            gridAutoRows: `${tileH}px`,
            columnGap: tileGapX,
            rowGap: tileGapY,
          }}
        >
          {Array.from({length: 15}).map((_, i) => {
            const src = TILES[i % TILES.length];
            return (
              <div
                key={i}
                style={{
                  width: tileW,
                  height: tileH,
                  borderRadius: 16,
                  overflow: "hidden",
                  background: "#E5E0D6",
                  boxShadow: "0 6px 16px rgba(30,24,12,0.06)",
                }}
              >
                <Img
                  src={staticFile(src)}
                  style={{
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                    display: "block",
                  }}
                />
              </div>
            );
          })}
        </div>

        {/* Translucent paper wash to dim the grid behind the card. */}
        <AbsoluteFill style={{background: PAPER_PROMPT, opacity: bgWashOpacity}} />
      </div>

      {/* ───── Prompt card (beat 1) ───── */}
      <div
        style={{
          position: "absolute",
          top: promptCardY,
          left: promptCardX,
          width: promptCardW,
          opacity: cardOpacity,
        }}
      >
        <div
          style={{
            background: "#fff",
            borderRadius: 24,
            padding: "44px 56px 32px",
            boxShadow:
              "0 28px 60px rgba(40,30,16,0.10), 0 6px 16px rgba(40,30,16,0.05)",
            minHeight: 230,
            position: "relative",
          }}
        >
          <div
            style={{
              fontSize: 44,
              fontWeight: 500,
              color: INK,
              lineHeight: 1.28,
              letterSpacing: -0.8,
              minHeight: 132,
            }}
          >
            <span>{typedHead}</span>
            <span style={{color: tailColor}}>{typedTail}</span>
          </div>

          {/* Bottom row: + left, model+send right */}
          <div
            style={{
              marginTop: 26,
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
            }}
          >
            <svg width={36} height={36} viewBox="0 0 24 24" style={{display: "block"}}>
              <path
                d="M12 5V19M5 12H19"
                stroke={INK}
                strokeWidth={2.2}
                strokeLinecap="round"
              />
            </svg>
            <div style={{display: "flex", alignItems: "center", gap: 24}}>
              <div style={{display: "flex", alignItems: "center", gap: 8}}>
                <span style={{fontSize: 28, color: INK, fontWeight: 500, letterSpacing: -0.2}}>Opus 4.7</span>
                <svg width={22} height={22} viewBox="0 0 24 24">
                  <path
                    d="M6 9L12 15L18 9"
                    stroke={INK}
                    strokeWidth={2.2}
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    fill="none"
                  />
                </svg>
              </div>
              <div
                style={{
                  position: "relative",
                  width: 64,
                  height: 64,
                  borderRadius: 14,
                  background: BURNT,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  transform: `scale(${buttonClick})`,
                  boxShadow: "0 4px 10px rgba(192,83,59,0.28)",
                }}
              >
                <SendArrow size={34} />
              </div>
            </div>
          </div>

          {/* Cursor */}
          <div
            style={{
              position: "absolute",
              right: 18 + cursorDX,
              bottom: -68 + cursorDY,
              opacity: cursorVis,
              pointerEvents: "none",
            }}
          >
            <HandCursor size={88} />
          </div>
        </div>
      </div>

      {/* ───── White-wash transition ───── */}
      <AbsoluteFill style={{background: PAPER, opacity: whiteWash, pointerEvents: "none"}} />

      {/* ───── Dashboard: title + stat cards + chart ───── */}
      <AbsoluteFill style={{opacity: whiteWash}}>
        {/* Hero title — serif with left-to-right reveal via clipPath */}
        <div
          style={{
            position: "absolute",
            top: 100,
            left: 156,
            opacity: titleVis,
            fontFamily: "Georgia, 'Times New Roman', serif",
            fontSize: 92,
            fontWeight: 500,
            letterSpacing: -2.6,
            color: INK,
            lineHeight: 1.0,
            clipPath: `polygon(0 0, ${titleSweep}% 0, ${titleSweep}% 100%, 0 100%)`,
          }}
        >
          {HERO_TITLE}
        </div>

        {/* Stat cards row */}
        <div
          style={{
            position: "absolute",
            top: 270,
            left: 156,
            right: 156,
            display: "flex",
            gap: 26,
          }}
        >
          {[
            {label: "Spend", value: spendVal, delta: "62.0%", pos: true},
            {label: "Purchases", value: purchVal, delta: "78.4%", pos: true},
            {label: "CPA", value: cpaVal, delta: "9.6%", pos: false},
            {label: "ROAS", value: roasVal, delta: "31.0%", pos: true},
          ].map((s, i) => (
            <div
              key={s.label}
              style={{
                flex: 1,
                opacity: statStyles[i].opacity,
                transform: statStyles[i].transform,
              }}
            >
              <StatCard
                label={s.label}
                value={s.value}
                delta={s.delta}
                deltaPositive={s.pos}
              />
            </div>
          ))}
        </div>

        {/* Chart area */}
        <ChartArea
          frame={frame}
          opacity={chartOpacity}
          blueSeries={blueSeries}
          greenSeries={greenSeries}
          blueProg={blueProg}
          greenProg={greenProg}
        />
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

// ──────────────────────────────────────────────────────────────────────────────
// Chart component (kept inside this file — local to the scene)
// ──────────────────────────────────────────────────────────────────────────────
const ChartArea: React.FC<{
  frame: number;
  opacity: number;
  blueSeries: number[];
  greenSeries: number[];
  blueProg: number;
  greenProg: number;
}> = ({opacity, blueSeries, greenSeries, blueProg, greenProg}) => {
  const left = 156;
  const right = 1764;
  const top = 480;
  const bottom = 980;
  const w = right - left;
  const h = bottom - top;
  // Inset for plotting area
  const plotL = 60;
  const plotR = 60;
  const plotT = 24;
  const plotB = 70;
  const innerL = left + plotL;
  const innerR = right - plotR;
  const innerT = top + plotT;
  const innerB = bottom - plotB;
  const innerW = innerR - innerL;
  const innerH = innerB - innerT;

  const n = blueSeries.length;

  // Y-axis ranges
  const blueMin = 60;
  const blueMax = 260;
  const greenMin = 2;
  const greenMax = 16;

  const blueToY = (v: number) =>
    innerB - ((v - blueMin) / (blueMax - blueMin)) * innerH;
  const greenToY = (v: number) =>
    innerB - ((v - greenMin) / (greenMax - greenMin)) * innerH;
  const xAt = (i: number) => innerL + (i / (n - 1)) * innerW;

  // Series values are already in axis units (Spend $60..$260, Purchases 2..16).
  const bluePts = blueSeries.map((v, i) => ({x: xAt(i), y: blueToY(v)}));
  const greenPts = greenSeries.map((v, i) => ({x: xAt(i), y: greenToY(v)}));

  const blueVisibleCount = Math.max(0, Math.ceil(blueProg * n));
  const greenVisibleCount = Math.max(0, Math.ceil(greenProg * n));

  const bluePath = smoothPath(bluePts, blueVisibleCount);
  const greenPath = smoothPath(greenPts, greenVisibleCount);

  // Legend appears when blue starts visible.
  const legendOpacity = blueProg > 0.02 ? 1 : 0;
  const greenLegendOpacity = greenProg > 0.02 ? 1 : 0;

  // Y-axis label rows
  const yLeftLabels = ["$260", "$220", "$200", "$180", "$140", "$100", "$60"];
  const yRightLabels = ["16", "14", "12", "10", "8", "6", "4", "2"];

  return (
    <div
      style={{
        position: "absolute",
        left,
        top,
        width: w,
        height: h,
        opacity,
      }}
    >
      <svg width={w} height={h} style={{display: "block"}}>
        {/* Subtle horizontal gridline at "midline" */}
        <line
          x1={plotL}
          x2={w - plotR}
          y1={innerB - innerH * 0.45 - top}
          y2={innerB - innerH * 0.45 - top}
          stroke={GRID_LINE}
          strokeWidth={1}
        />
        {/* Subtle vertical division lines at 1/3 and 2/3 */}
        {[0.33, 0.66].map((t, i) => {
          const x = plotL + t * innerW;
          return (
            <line
              key={i}
              x1={x}
              x2={x}
              y1={plotT}
              y2={h - plotB}
              stroke={GRID_LINE}
              strokeWidth={1}
            />
          );
        })}

        {/* Y-axis labels left */}
        {yLeftLabels.map((lab, i) => {
          const t = i / (yLeftLabels.length - 1);
          const y = plotT + t * (h - plotT - plotB);
          return (
            <text
              key={lab}
              x={6}
              y={y + 6}
              fontSize={22}
              fill="#E2DCCC"
              fontFamily="inherit"
              fontWeight={500}
            >
              {lab}
            </text>
          );
        })}
        {/* Y-axis labels right */}
        {yRightLabels.map((lab, i) => {
          const t = i / (yRightLabels.length - 1);
          const y = plotT + t * (h - plotT - plotB);
          return (
            <text
              key={lab}
              x={w - plotR + 14}
              y={y + 6}
              fontSize={22}
              fill="#E2DCCC"
              fontFamily="inherit"
              fontWeight={500}
            >
              {lab}
            </text>
          );
        })}

        {/* Blue curve - drawn in SVG coords (absolute pts include left/top offset) */}
        {/* We baked left/top into pts; SVG is positioned at left,top so subtract */}
        <g transform={`translate(${-left} ${-top})`}>
          <path
            d={bluePath}
            stroke={CHART_BLUE}
            strokeWidth={6}
            fill="none"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
          <path
            d={greenPath}
            stroke={CHART_GREEN}
            strokeWidth={7}
            fill="none"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeDasharray="2 12"
          />
        </g>
      </svg>

      {/* Legend pills */}
      <div
        style={{
          position: "absolute",
          bottom: 4,
          left: 0,
          width: "100%",
          display: "flex",
          justifyContent: "center",
          gap: 22,
        }}
      >
        <LegendPill
          color={CHART_BLUE}
          label="Spend ($)"
          opacity={legendOpacity}
          dashed={false}
        />
        <LegendPill
          color={CHART_GREEN}
          label="Purchases"
          opacity={greenLegendOpacity}
          dashed
        />
      </div>
    </div>
  );
};

const LegendPill: React.FC<{
  color: string;
  label: string;
  opacity: number;
  dashed: boolean;
}> = ({color, label, opacity, dashed}) => (
  <div
    style={{
      opacity,
      background: "#fff",
      borderRadius: 16,
      padding: "10px 20px",
      display: "flex",
      alignItems: "center",
      gap: 12,
      boxShadow: "0 2px 6px rgba(0,0,0,0.05)",
    }}
  >
    {dashed ? (
      <div style={{display: "flex", gap: 3}}>
        {[0, 1, 2].map((i) => (
          <span
            key={i}
            style={{
              width: 6,
              height: 18,
              background: color,
              borderRadius: 2,
              display: "block",
            }}
          />
        ))}
      </div>
    ) : (
      <span
        style={{
          width: 22,
          height: 22,
          background: color,
          borderRadius: 5,
          display: "block",
        }}
      />
    )}
    <span style={{fontSize: 26, color: INK, fontWeight: 500, letterSpacing: -0.2}}>
      {label}
    </span>
  </div>
);

// ──────────────────────────────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────────────────────────────
function formatDollarK(n: number): string {
  if (n >= 1000) {
    const k = n / 1000;
    if (k >= 10) return `$${Math.round(k)}K`;
    return `$${k.toFixed(1)}K`;
  }
  return `$${Math.round(n)}`;
}

function blendHex(a: string, b: string, t: number): string {
  const pa = hexToRgb(a);
  const pb = hexToRgb(b);
  const r = Math.round(pa.r + (pb.r - pa.r) * t);
  const g = Math.round(pa.g + (pb.g - pa.g) * t);
  const bl = Math.round(pa.b + (pb.b - pa.b) * t);
  return `rgb(${r}, ${g}, ${bl})`;
}

function hexToRgb(hex: string): {r: number; g: number; b: number} {
  const h = hex.replace("#", "");
  return {
    r: parseInt(h.slice(0, 2), 16),
    g: parseInt(h.slice(2, 4), 16),
    b: parseInt(h.slice(4, 6), 16),
  };
}

// Keep imports referenced (RED_DELTA unused in current StatCard).
void RED_DELTA;
