import React from "react";
import {AbsoluteFill, Img, interpolate, staticFile, useCurrentFrame} from "remotion";
import {FONT_FAMILY, clamped} from "../helpers";

// =============================================================================
// Scene 09 — segment_008 — "Top 5 of 20 — sorted by ROAS" ranked-card row.
//
// Source: 30 frames @ 25fps (3s). Recreated as 90 frames @ 30fps.
// Source N → Remotion local ≈ 3*(N-1). Scene starts at Remotion 1262.
//
// What the source shows (eye-test on f001..f030 + Gemini Q1..Q4):
// ----------------------------------------------------------------------------
//   • f001..f002 carry-over: prior scene dashboard fades out fast.
//   • f003..f005 (local 6..14): off-white paper background; the serif hero
//     "Top 5 of 20" fades in upper-left, with "Sorted by ROAS" + small blue
//     Facebook logo below it.
//   • f005..f010 (local 14..29): five 9:16 phone cards stagger-in left to
//     right with a small fade + lift, each carrying a "#N" blue rounded
//     pill at top-left and a Facebook + Instagram glyph pair at top-right.
//     Right after each card lands, a "ROAS / Nx" label appears beneath it
//     (label left, light-blue pill right).
//   • f010..f028 (local 29..81): static hold on the five-card row. Cards
//     have a very slight breathing / micro-bob to suggest live UGC video
//     playback (card #3 shows a noticeable pan/scroll in the source).
//   • f029..f030 (local 81..89): final wash to white for the hand-off.
// =============================================================================

// 5 ranked-card assets generated by scripts/gen_scene09.py.
const CARDS = [
  "/aigen/scene09/r1_dark_flame_macro.png",        // #1 — 4.2x
  "/aigen/scene09/r2_boutique_microphone.png",     // #2 — 3.8x
  "/aigen/scene09/r3_balcony_hand_pouch.png",      // #3 — 3.4x
  "/aigen/scene09/r4_yellow_hoodie_giant_pouch.png", // #4 — 3.0x
  "/aigen/scene09/r5_fridge_hand_place.png",       // #5 — 2.7x
];

const ROAS_VALUES = ["4.2x", "3.8x", "3.4x", "3.0x", "2.7x"];

// Palette — matches Scene 08 dashboard hand-off for visual continuity.
const PAPER = "#F6F4EE";          // off-white paper background
const INK = "#1A1A1A";            // primary text
const INK_SOFT = "#8A8680";       // subline grey
const FB_BLUE = "#1877F2";        // Facebook brand blue
const PILL_BG = "#EEF3FD";        // very light pale-blue rounded pill bg (faint)
const PILL_TEXT = "#6B8FE0";      // softer mid-blue pill text (less saturated than FB)
const HASH_PILL_TEXT = "#2E72E8"; // #N pill blue text (slightly brighter)
const CARD_FALLBACK = "#E5E0D6";  // graceful fallback before assets load

// ──────────────────────────────────────────────────────────────────────────────
// Small SVG glyphs
// ──────────────────────────────────────────────────────────────────────────────
const FacebookCircle: React.FC<{size: number; color?: string}> = ({
  size,
  color = FB_BLUE,
}) => (
  <svg width={size} height={size} viewBox="0 0 32 32" style={{display: "block"}}>
    <circle cx={16} cy={16} r={16} fill={color} />
    <path
      d="M18.4 16.6h2.1l.32-2.66h-2.42v-1.7c0-.77.21-1.3 1.3-1.3h1.4V8.55c-.24-.03-1.07-.1-2.05-.1-2.03 0-3.42 1.24-3.42 3.52v1.97h-2.3v2.66h2.3V23.4h2.77v-6.8z"
      fill="#fff"
    />
  </svg>
);

// Outline Facebook 'f' (used inside the card-top icons — outlined style).
const FacebookOutline: React.FC<{size: number; color?: string}> = ({
  size,
  color = "#111",
}) => (
  <svg width={size} height={size} viewBox="0 0 32 32" style={{display: "block"}}>
    <circle cx={16} cy={16} r={14.5} stroke={color} strokeWidth={1.8} fill="none" />
    <path
      d="M18.3 16.6h2.1l.3-2.66h-2.4v-1.7c0-.77.2-1.3 1.3-1.3h1.4V8.55c-.24-.03-1.07-.1-2.05-.1-2.03 0-3.42 1.24-3.42 3.52v1.97h-2.3v2.66h2.3V23.4h2.77v-6.8z"
      fill={color}
    />
  </svg>
);

const InstagramOutline: React.FC<{size: number; color?: string}> = ({
  size,
  color = "#111",
}) => (
  <svg width={size} height={size} viewBox="0 0 32 32" style={{display: "block"}}>
    <rect
      x={4.5}
      y={4.5}
      width={23}
      height={23}
      rx={6.5}
      stroke={color}
      strokeWidth={1.8}
      fill="none"
    />
    <circle cx={16} cy={16} r={5.4} stroke={color} strokeWidth={1.8} fill="none" />
    <circle cx={22.5} cy={9.5} r={1.25} fill={color} />
  </svg>
);

// "#N" pill at top-left of every card.
const RankPill: React.FC<{n: number}> = ({n}) => (
  <div
    style={{
      background: "#fff",
      borderRadius: 14,
      padding: "5px 14px",
      fontSize: 22,
      fontWeight: 500,
      color: HASH_PILL_TEXT,
      letterSpacing: -0.2,
      boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
      lineHeight: 1,
    }}
  >
    #{n}
  </div>
);

// Light-blue rounded pill for the "Nx" ROAS multiplier.
const RoasPill: React.FC<{value: string}> = ({value}) => (
  <div
    style={{
      background: PILL_BG,
      borderRadius: 14,
      padding: "6px 18px",
      fontSize: 24,
      fontWeight: 500,
      color: PILL_TEXT,
      letterSpacing: -0.2,
      lineHeight: 1,
    }}
  >
    {value}
  </div>
);

// Carry-over chart silhouette — quick fade-out reproduction of Scene 08's
// dashboard so the transition into Scene 09's paper feels continuous instead
// of a hard cut. Includes the serif title, four stat cards, and a simplified
// pair of trend curves so the recreation matches the source's f001..f002 state.
const STAT_CARD_VALUES: Array<{label: string; value: string; delta: string}> = [
  {label: "Spend", value: "$4.8K", delta: "↑62.0%"},
  {label: "Purchases", value: "218", delta: "↑78.4%"},
  {label: "CPA", value: "$22.00", delta: "↓9.6%"},
  {label: "ROAS", value: "3.4x", delta: "↑31.0%"},
];

const CarryChart: React.FC<{opacity: number}> = ({opacity}) => (
  <div style={{position: "absolute", inset: 0, opacity, pointerEvents: "none"}}>
    {/* Hero serif title (matches Scene 08 exactly) */}
    <div
      style={{
        position: "absolute",
        top: 100,
        left: 156,
        fontFamily: "Georgia, 'Times New Roman', serif",
        fontSize: 92,
        fontWeight: 500,
        color: "#1A1A1A",
        letterSpacing: -2,
        lineHeight: 1,
      }}
    >
      Ads insights performance trend
    </div>
    {/* Stat cards row — four white rounded cards stretched across the canvas. */}
    <div
      style={{
        position: "absolute",
        top: 270,
        left: 156,
        right: 156,
        display: "flex",
        gap: 28,
      }}
    >
      {STAT_CARD_VALUES.map((s) => {
        const positive = s.delta.startsWith("↑");
        return (
          <div
            key={s.label}
            style={{
              flex: 1,
              background: "#fff",
              border: "1px solid #E8E4DA",
              borderRadius: 18,
              padding: "26px 32px 28px",
              boxShadow: "0 1px 2px rgba(0,0,0,0.025)",
            }}
          >
            <div
              style={{
                fontSize: 26,
                color: "#8A8680",
                fontWeight: 500,
                letterSpacing: -0.1,
              }}
            >
              {s.label}
            </div>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 18,
                marginTop: 10,
              }}
            >
              <div
                style={{
                  fontSize: 76,
                  fontWeight: 650,
                  color: "#1A1A1A",
                  letterSpacing: -2.0,
                  lineHeight: 1,
                }}
              >
                {s.value}
              </div>
              <div
                style={{
                  fontSize: 26,
                  color: "#1FB55C",
                  fontWeight: 500,
                  marginTop: 4,
                }}
              >
                {positive ? "↑" : "↓"}
                {s.delta.slice(1)}
              </div>
            </div>
          </div>
        );
      })}
    </div>
    {/* Y-axis labels (left $260..$60) — light grey */}
    <div
      style={{
        position: "absolute",
        left: 100,
        top: 520,
        height: 460,
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        fontSize: 26,
        color: "#CFCAB6",
        fontWeight: 500,
      }}
    >
      <span>$260</span>
      <span>$220</span>
      <span>$200</span>
      <span>$180</span>
      <span>$140</span>
      <span>$100</span>
      <span>$60</span>
    </div>
    {/* Y-axis labels (right 16..2) */}
    <div
      style={{
        position: "absolute",
        right: 100,
        top: 520,
        height: 460,
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        fontSize: 26,
        color: "#CFCAB6",
        fontWeight: 500,
      }}
    >
      <span>16</span>
      <span>14</span>
      <span>12</span>
      <span>10</span>
      <span>8</span>
      <span>6</span>
      <span>4</span>
      <span>2</span>
    </div>
    {/* Chart trend curves */}
    <svg
      width={1500}
      height={500}
      viewBox="0 0 1500 500"
      style={{position: "absolute", left: 200, top: 510}}
    >
      <path
        d="M 0 430 Q 80 400 160 410 Q 240 380 320 360 Q 400 330 480 340 Q 560 290 640 270 Q 720 230 800 240 Q 880 200 960 160 Q 1040 180 1120 130 Q 1200 100 1280 80 Q 1360 60 1440 40"
        stroke="#3B82F6"
        strokeWidth={5}
        fill="none"
        strokeLinecap="round"
      />
      <path
        d="M 0 450 Q 80 420 160 430 Q 240 405 320 388 Q 400 360 480 372 Q 560 320 640 300 Q 720 260 800 270 Q 880 240 960 200 Q 1040 220 1120 175 Q 1200 145 1280 125 Q 1360 105 1440 85"
        stroke="#22C55E"
        strokeWidth={5}
        fill="none"
        strokeDasharray="6 8"
        strokeLinecap="round"
      />
    </svg>
    {/* Legend pills at bottom */}
    <div
      style={{
        position: "absolute",
        bottom: 64,
        left: 0,
        right: 0,
        display: "flex",
        justifyContent: "center",
        gap: 28,
      }}
    >
      <div
        style={{
          background: "#fff",
          borderRadius: 18,
          padding: "8px 18px",
          display: "flex",
          alignItems: "center",
          gap: 10,
          fontSize: 22,
          color: "#1A1A1A",
          fontWeight: 500,
          boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
        }}
      >
        <div
          style={{
            width: 18,
            height: 14,
            background: "#3B82F6",
            borderRadius: 3,
          }}
        />
        Spend ($)
      </div>
      <div
        style={{
          background: "#fff",
          borderRadius: 18,
          padding: "8px 18px",
          display: "flex",
          alignItems: "center",
          gap: 10,
          fontSize: 22,
          color: "#1A1A1A",
          fontWeight: 500,
          boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
        }}
      >
        <svg width={20} height={14}>
          <line
            x1={0}
            y1={7}
            x2={20}
            y2={7}
            stroke="#22C55E"
            strokeWidth={3}
            strokeDasharray="3 4"
          />
        </svg>
        Purchases
      </div>
    </div>
  </div>
);

// ──────────────────────────────────────────────────────────────────────────────
// Layout constants — derived from f015 (a clean settled frame) at 1920x1080.
// Source measurements (scaled): card ~258w x ~555h, gap ~36px, row baseline
// at ~y260, ROAS label row at ~y855.
// ──────────────────────────────────────────────────────────────────────────────
const W = 1920;

const CARD_W = 258;
const CARD_H = 555;
const CARD_GAP = 34;
const ROW_LEFT = 105;
const ROW_TOP = 245;
const CARD_RADIUS = 16;

const LABEL_GAP = 30; // between card bottom and label baseline row

// Title block (per Gemini Q1)
const TITLE_LEFT = 105;
const TITLE_TOP = 75;
const SUBLINE_TOP = 155;

// ──────────────────────────────────────────────────────────────────────────────
// Scene
// ──────────────────────────────────────────────────────────────────────────────
export const Scene09Seg008: React.FC = () => {
  const frame = useCurrentFrame();

  // Scene 08 hands off at frame 1261 on a populated chart. Source f001..f002
  // (local r=0..5) still show the dashboard chart; by f003 (r=6) the canvas
  // is paper. We reproduce a quick fading silhouette of the chart for the
  // first ~6 local frames so the cut isn't jarring.
  const carryOpacity = interpolate(frame, [0, 6], [1, 0], clamped);

  // Title block fade-in — Gemini Q3: serif title fades in at f003..f004 (r=6..9).
  const titleVis = interpolate(frame, [6, 12], [0, 1], clamped);
  const titleY = interpolate(frame, [6, 12], [10, 0], clamped);
  // Subline + FB logo: f004..f005 (r=9..12).
  const sublineVis = interpolate(frame, [9, 14], [0, 1], clamped);

  // 5-card stagger entry — cards enter ~1 src-frame (3 local frames) apart
  // so by f011 (r=30) all five are settled. This matches the source's
  // snappy reveal where by source f010 every card is visible.
  const cardDelays = [12, 15, 18, 21, 24];

  // ROAS label delays — labels appear ~2 src-frames after each card lands.
  const labelDelays = [18, 21, 24, 27, 30];

  // Final wash to white for hand-off — Gemini Q3 (g): only the last source
  // frame (f030 → r≈87) cuts to blank white. Quick wash over the last ~6 frames.
  const exitWash = interpolate(frame, [84, 89], [0, 1], clamped);

  // Per-card subtle vertical bob (~ live UGC playback).
  const bob = (i: number) => Math.sin((frame / 28) + i * 0.71) * 1.2;

  // Card #3 has a slightly stronger pan (the source shows a building / street
  // scrolling) — we simulate via a soft vertical shift on its inner Img only.
  const card3Pan = interpolate(frame, [30, 89], [0, -34], clamped);

  return (
    <AbsoluteFill
      style={{background: PAPER, fontFamily: FONT_FAMILY, color: INK}}
    >
      {/* ───── Carry-over chart silhouette (Scene 08 hand-off) ───── */}
      {carryOpacity > 0.01 ? <CarryChart opacity={carryOpacity} /> : null}

      {/* ───── Hero title ───── */}
      <div
        style={{
          position: "absolute",
          left: TITLE_LEFT,
          top: TITLE_TOP,
          fontFamily: "Georgia, 'Times New Roman', serif",
          fontSize: 65,
          fontWeight: 500,
          letterSpacing: -1.2,
          color: INK,
          opacity: titleVis,
          transform: `translateY(${titleY}px)`,
          lineHeight: 1,
        }}
      >
        Top 5 of 20
      </div>

      {/* ───── Subline ───── */}
      <div
        style={{
          position: "absolute",
          left: TITLE_LEFT,
          top: SUBLINE_TOP,
          display: "flex",
          alignItems: "center",
          gap: 12,
          fontFamily: "Georgia, 'Times New Roman', serif",
          fontSize: 30,
          fontWeight: 400,
          color: INK_SOFT,
          letterSpacing: -0.3,
          opacity: sublineVis,
          lineHeight: 1,
        }}
      >
        <span>Sorted by ROAS</span>
        <FacebookCircle size={28} />
      </div>

      {/* ───── 5 ranked cards ───── */}
      {CARDS.map((src, i) => {
        const delay = cardDelays[i];
        const labelDelay = labelDelays[i];
        // Quicker per-card entry (~4 frames at 30fps ≈ 1 src-frame), matching
        // the source's snappy card-pop.
        const cardVis = interpolate(frame, [delay, delay + 4], [0, 1], clamped);
        const cardY = interpolate(frame, [delay, delay + 4], [14, 0], clamped);
        const labelVis = interpolate(frame, [labelDelay, labelDelay + 4], [0, 1], clamped);

        const x = ROW_LEFT + i * (CARD_W + CARD_GAP);
        const y = ROW_TOP + bob(i);

        return (
          <React.Fragment key={i}>
            {/* Card */}
            <div
              style={{
                position: "absolute",
                left: x,
                top: y,
                width: CARD_W,
                height: CARD_H,
                borderRadius: CARD_RADIUS,
                overflow: "hidden",
                background: CARD_FALLBACK,
                boxShadow:
                  "0 18px 36px rgba(30,24,12,0.05), 0 4px 10px rgba(30,24,12,0.03)",
                opacity: cardVis,
                transform: `translateY(${cardY}px)`,
              }}
            >
              <Img
                src={staticFile(src)}
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                  display: "block",
                  transform: i === 2 ? `translateY(${card3Pan}px) scale(1.06)` : undefined,
                }}
              />

              {/* Top-left rank pill */}
              <div style={{position: "absolute", top: 14, left: 14}}>
                <RankPill n={i + 1} />
              </div>

              {/* Top-right FB + IG glyphs — solid white outline so they
                  read on every card background (dark and light). */}
              <div
                style={{
                  position: "absolute",
                  top: 16,
                  right: 14,
                  display: "flex",
                  gap: 10,
                  alignItems: "center",
                  filter: "drop-shadow(0 1px 2px rgba(0,0,0,0.35))",
                }}
              >
                <FacebookOutline size={26} color="#fff" />
                <InstagramOutline size={26} color="#fff" />
              </div>
            </div>

            {/* Caption row below card (ROAS label + Nx pill) */}
            <div
              style={{
                position: "absolute",
                left: x,
                top: y + CARD_H + LABEL_GAP,
                width: CARD_W,
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                opacity: labelVis,
              }}
            >
              <div
                style={{
                  fontSize: 22,
                  fontWeight: 500,
                  color: "#2A2A2A",
                  letterSpacing: 0.35,
                }}
              >
                ROAS
              </div>
              <RoasPill value={ROAS_VALUES[i]} />
            </div>
          </React.Fragment>
        );
      })}

      {/* ───── Final wash to white for hand-off ───── */}
      <AbsoluteFill
        style={{background: PAPER, opacity: exitWash, pointerEvents: "none"}}
      />
    </AbsoluteFill>
  );
};
