import React from "react";
import {AbsoluteFill, Img, interpolate, staticFile, useCurrentFrame} from "remotion";
import {FONT_FAMILY, clamped, seeded} from "../helpers";

// =============================================================================
// Scene 10 — segment_009 — "Generating videos / Detecting winning patterns",
// followed by "Automate this process every Monday." prompt + the Higgsfield MCP
// logo reveal.
//
// Source: 60 frames @ 25fps (2.4s). Recreated as 180 frames @ 30fps.
// Source N → Remotion local r ≈ 3*(N-1). Scene starts at Remotion 1352.
//
// Beat map (local Remotion frames inside the 180-frame scene):
//   0..18      Phase A entry — left-half masonry grid of UGC creator-content
//              cards staggers in (8 tiles), serif hero "Generating videos"
//              types/draws L→R on the right; subline "Detecting winning
//              patterns" fades in below it.
//   18..52     Phase A hold — grid sustained, subtle UGC bob, title with "..."
//   52..56     Phase B start — grid dims/desaturates, white input bar slides
//              up from below and lands; "+" icon, "Opus 4.7 v", red send
//              button are revealed.
//   56..140    Sentence "Automate this process every Monday." types in
//              letter-by-letter inside the input bar (steady cadence).
//   110..150   Hand-pointer cursor approaches the red send button from
//              below-right.
//   150..160   Button press / scale-down nudge.
//   160..168   Wash to off-white.
//   168..180   "Higgsfield MCP" logomark + wordmark fades in centered with
//              a gentle scale-up — handoff into Scene 11.
// =============================================================================

// Palette
const PAPER = "#F5F2EC";            // warm off-white background (matches Sc09 hand-off)
const INK = "#1A1A1A";              // primary near-black
const SUBLINE = "#7A766F";          // subline grey
const BURNT = "#C0533B";            // red send button (matches Sc08 prompt scene)
const HF_GREY = "#3F3F3F";          // Higgsfield wordmark grey
const HF_MCP = "#7A7A7A";           // MCP superscript grey

// 8 masonry-grid card assets generated by scripts/gen_scene10.py.
const TILES = [
  "/aigen/scene10/c1_boutique_giant_pouch.png",
  "/aigen/scene10/c2_fan_of_pouches.png",
  "/aigen/scene10/c3_pouch_close_creator.png",
  "/aigen/scene10/c4_kitchen_creator_selfie.png",
  "/aigen/scene10/c5_balcony_handheld_pouch.png",
  "/aigen/scene10/c6_gradient_promo_bottle.png",
  "/aigen/scene10/c7_apartment_window_pouch.png",
  "/aigen/scene10/c8_pouches_overhead_wood.png",
];

// Masonry-grid layout — left half of canvas.
// 3 columns at slightly different y-offsets, each holds a tall + a shorter
// card so the row staggers like a Pinterest grid. Per Gemini Q1 measurements
// the grid occupies x:25..1080, with ~335px-wide cards, 25px gaps, ~15px radius.

const COL_W = 335;        // 9:16 card column width (per Gemini)
const COL_X = [25, 385, 745];        // x position of each column (per Gemini)
const COL_Y_OFFSET = [-145, -400, -50];  // vertical start offsets (col2 deeper up)
const ROW_GAPS = [25, 25, 25];       // gap between two stacked cards
// per-column heights for the two visible tiles (~9:16 of 335 = ~586 each)
const TILE_HEIGHTS: Array<[number, number]> = [
  [586, 586],   // col 0
  [586, 586],   // col 1 (deeper offset gives us the staggered look)
  [586, 586],   // col 2
];

// Pull from TILES[0..7] in display order so the grid uses all 8.
const TILES_BY_SLOT: Array<{col: number; row: number; src: string}> = [
  {col: 0, row: 0, src: TILES[0]}, // boutique giant pouch
  {col: 0, row: 1, src: TILES[4]}, // balcony handheld pouch
  {col: 1, row: 0, src: TILES[1]}, // fan of pouches (top, short)
  {col: 1, row: 1, src: TILES[2]}, // pouch-close creator (bottom, tall)
  {col: 2, row: 0, src: TILES[3]}, // kitchen creator selfie
  {col: 2, row: 1, src: TILES[5]}, // gradient promo bottle
];
// Two more tiles reserved as off-screen filler (bottom poke-ins of col 1 and
// col 2 hide partially off canvas, per Gemini Q1 — column 2 row 3 at y~1172
// and column 1 row 3 at y~822..1408).
const EDGE_TILES = [
  {col: 1, src: TILES[6], y: 822, h: 586},   // c7 apartment window pouch at bottom of col 1
  {col: 2, src: TILES[7], y: 1172, h: 586},  // c8 wood-flat-lay at bottom of col 2 (mostly off screen)
];

const CARD_RADIUS = 15;
const W = 1920;
const H = 1080;

// Right-half text block (Gemini Q1)
const TITLE_X = 1165;
const TITLE_Y = 480;
const TITLE_SIZE = 72;
const SUBLINE_SIZE = 30;

// Input bar (Phase B) — Gemini Q1
const BAR_W = 1784;
const BAR_H = 320;
const BAR_X = 68;
const BAR_Y = 365;
const BAR_RADIUS = 32;     // mid-range of 28-32
const SEND_BTN = 80;       // red square side (Gemini)
const SEND_RADIUS = 16;
const PLUS_SIZE = 44;

const PROMPT_TEXT = "Automate this process every Monday.";

// ──────────────────────────────────────────────────────────────────────────────
// Sub-components
// ──────────────────────────────────────────────────────────────────────────────

const SendArrow: React.FC<{size: number}> = ({size}) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    style={{display: "block"}}
  >
    <path
      d="M12 19V5M12 5L6 11M12 5L18 11"
      stroke="#fff"
      strokeWidth={1.8}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

const PlusIcon: React.FC<{size: number; color?: string}> = ({size, color = INK}) => (
  <svg width={size} height={size} viewBox="0 0 24 24" style={{display: "block"}}>
    <path
      d="M12 5V19M5 12H19"
      stroke={color}
      strokeWidth={1.6}
      strokeLinecap="round"
    />
  </svg>
);

const ChevronDown: React.FC<{size: number; color?: string}> = ({
  size,
  color = INK,
}) => (
  <svg width={size} height={size} viewBox="0 0 24 24" style={{display: "block"}}>
    <path
      d="M6 9L12 15L18 9"
      stroke={color}
      strokeWidth={2.2}
      strokeLinecap="round"
      strokeLinejoin="round"
      fill="none"
    />
  </svg>
);

// Hand-pointer cursor (outlined "pointing finger" cursor that hovers over
// the send button). Same look as Scene 08's cursor.
const HandCursor: React.FC<{size: number}> = ({size}) => (
  <svg width={size} height={size * 1.15} viewBox="0 0 40 46" style={{display: "block"}}>
    <path
      d="M14 4 V22 L9 24 C6 26 6 30 8 33 L14 42 H30 L33 32 V20 C33 18 31 17 30 17 C29 17 27 18 27 20 V12 C27 10 25 9 24 9 C23 9 22 10 22 12 V8 C22 6 20 5 19 5 C18 5 17 6 17 8 V4 C17 2 16 1 15 1 C14 1 13 2 13 4 Z"
      fill="#fff"
      stroke="#000"
      strokeWidth={1.8}
      strokeLinejoin="round"
    />
  </svg>
);

// Higgsfield squiggle logomark — wavy 'S'/'∽' shape.
const HiggsfieldMark: React.FC<{size: number; color?: string}> = ({
  size,
  color = HF_GREY,
}) => (
  <svg width={size * 1.4} height={size} viewBox="0 0 56 40" style={{display: "block"}}>
    <path
      d="M6 20 C 10 8, 18 8, 22 20 S 34 32, 38 20 S 50 8, 50 20"
      stroke={color}
      strokeWidth={5}
      strokeLinecap="round"
      fill="none"
    />
  </svg>
);

// ──────────────────────────────────────────────────────────────────────────────
// Scene
// ──────────────────────────────────────────────────────────────────────────────
export const Scene10Seg009: React.FC = () => {
  const frame = useCurrentFrame();

  // ── Phase A: grid + title ──────────────────────────────────────────────
  // Carry-over wash from previous Scene 09 (paper). We start already on
  // paper, so no carry-fade is necessary, but we ease the grid in over the
  // first 0..18 local frames.

  // Per-tile fade-in delays (stagger like a masonry-fill). Start tiles
  // already-visible at frame 0 (source f001 is mid-fill, not empty).
  const tileDelays = [-4, -1, -3, 0, -2, 1];

  // Title typing — start mid-type: by local frame 0 (source f001) the title
  // shows "Gene..." (per Gemini Q3 mid-fill stage). Compress so all 17 chars
  // land by local frame 12 (≈ source f005).
  const titleText = "Generating videos";
  const titleProg = interpolate(frame, [-4, 12], [0, titleText.length], clamped);
  const titleVisibleChars = Math.max(0, Math.floor(titleProg));
  const titleDots = interpolate(frame, [12, 18], [0, 1], clamped);

  // Subline — fade in just after title settles.
  const sublineVis = interpolate(frame, [6, 16], [0, 1], clamped);

  // Phase A → B dim. Per source f025: grid is very low opacity ghost (~0.08)
  // and title is gone. Strong white wash over the grid is needed.
  const phaseADim = interpolate(frame, [48, 60], [1, 0.08], clamped);
  const titleDim = interpolate(frame, [40, 52], [1, 0], clamped);
  // White wash layer behind input bar (in front of grid) so the grid reads
  // as a faded ghost, not full color.
  const gridWash = interpolate(frame, [48, 62], [0, 0.88], clamped);

  // ── Phase B: input bar ──────────────────────────────────────────────
  // Bar slides up + fades in on frames 50..58.
  const barRise = interpolate(frame, [50, 58], [40, 0], clamped);
  const barOpacity = interpolate(frame, [50, 58], [0, 1], clamped);
  // Gemini Q3 (g): around f035..f040 (rem 102..117) the bar drifts upward
  // slightly to a centered position. Move it ~25px up over rem 100..120.
  const barDrift = interpolate(frame, [100, 120], [0, -28], clamped);

  // Sentence type-on. Per Gemini Q3: typing spans f019..f048 (rem 54..141).
  // Source f030 (rem 87) already shows "Automate this process every" (27 of
  // 35 chars), so the cadence is fast at the start and slows. We use a
  // single linear span [56..120] (~64 frames for 35 chars ≈ 1.8 per char)
  // which matches source f019..f040 well.
  const charsTotal = PROMPT_TEXT.length;
  const charProgress = interpolate(
    frame,
    [56, 120],
    [0, charsTotal],
    clamped,
  );
  const visibleChars = Math.max(0, Math.floor(charProgress));
  const typedText = PROMPT_TEXT.slice(0, visibleChars);

  // Caret blink (after typing finished)
  const caretBlink = visibleChars < charsTotal
    ? (Math.floor(frame / 8) % 2 === 0 ? 1 : 0)
    : 0;

  // Hand cursor — approaches from below-right and lands on the red button.
  // Per Gemini Q1: hand size ~60w x 80h, lands at finger-tip x≈1750 y≈640.
  // Per Gemini Q3 the cursor lands and presses around f048..f053 (rem 141..159).
  // Account for bar drift so the hand stays on the button after the bar drifts.
  const btnTipX = 1750;
  const btnTipY = 640 + barDrift;   // follow the bar drift
  const handX = interpolate(frame, [100, 142], [btnTipX + 130, btnTipX - 18], clamped);
  const handY = interpolate(frame, [100, 142], [btnTipY + 220, btnTipY + 6], clamped);
  const handOpacity = interpolate(frame, [100, 108], [0, 1], clamped);

  // Button press scale-down around rem 142..150 (source f048..f051).
  const btnScale = interpolate(
    frame,
    [140, 144, 150, 154],
    [1, 0.92, 0.96, 1],
    clamped,
  );

  // ── Phase C: wash to off-white ──────────────────────────────────────────
  // Per Gemini Q3: wash starts at f054 (rem 159) and is complete by f057
  // (rem 168). Run the wash slightly earlier so f55-f57 are clearly washed.
  const wash = interpolate(frame, [155, 162], [0, 1], clamped);

  // ── Phase D: Higgsfield MCP logo fade-in ──────────────────────────────
  // Per Gemini Q3: logo fades in f058..f060 (rem 171..177). Start the fade
  // slightly earlier so it's clearly visible by source f058 (rem 171).
  const logoOpacity = interpolate(frame, [162, 172], [0, 1], clamped);
  const logoScale = interpolate(frame, [162, 178], [0.92, 1], clamped);

  // Subtle bob on each tile to suggest live UGC playback.
  const rand = seeded(919);
  const bobPhase = Array.from({length: 6}, () => rand() * Math.PI * 2);
  const bob = (i: number) => Math.sin((frame / 36) + bobPhase[i]) * 1.4;

  return (
    <AbsoluteFill
      style={{background: PAPER, fontFamily: FONT_FAMILY, color: INK}}
    >
      {/* ─────────── Phase A: masonry-grid tiles ─────────── */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          opacity: phaseADim,
          pointerEvents: "none",
        }}
      >
        {/* Edge poke-in tiles (small slivers at canvas edges) */}
        {EDGE_TILES.map((t, i) => {
          const placeholderIn = interpolate(frame, [0 + i * 2, 8 + i * 2], [0, 1], clamped);
          const photoIn = interpolate(frame, [8 + i * 2, 24 + i * 2], [0, 1], clamped);
          return (
            <div
              key={`edge-${i}`}
              style={{
                position: "absolute",
                left: COL_X[t.col],
                top: t.y,
                width: COL_W,
                height: t.h,
                borderRadius: CARD_RADIUS,
                overflow: "hidden",
                background:
                  "linear-gradient(140deg, #F2D2CB 0%, #E8B5AC 45%, #D88B83 100%)",
                opacity: placeholderIn,
              }}
            >
              <Img
                src={staticFile(t.src)}
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                  display: "block",
                  opacity: photoIn,
                }}
              />
            </div>
          );
        })}

        {/* Main grid slots */}
        {TILES_BY_SLOT.map((slot, i) => {
          const delay = tileDelays[i];
          // Placeholder pink card appears immediately (delay-2..delay)
          const pStart = Math.max(0, delay - 2);
          const pEnd = Math.max(pStart + 1, delay + 2);
          const placeholderIn = interpolate(
            frame,
            [pStart, pEnd],
            [0, 1],
            clamped,
          );
          // Photo crossfades in over ~4 src-frames (12 rem-frames) starting
          // at delay+8 (≈ source f003..f005 per Gemini Q3 dissolve mapping)
          const photoIn = interpolate(frame, [delay + 8, delay + 24], [0, 1], clamped);
          const yShift = interpolate(frame, [delay, delay + 8], [22, 0], clamped);

          // Compute y from column offset + previous tile heights
          const colY = COL_Y_OFFSET[slot.col];
          const prevH = slot.row === 0 ? 0 : TILE_HEIGHTS[slot.col][0] + ROW_GAPS[slot.col];
          const h = TILE_HEIGHTS[slot.col][slot.row];
          const x = COL_X[slot.col];
          const y = colY + prevH + bob(i) + yShift;

          return (
            <div
              key={`slot-${i}`}
              style={{
                position: "absolute",
                left: x,
                top: y,
                width: COL_W,
                height: h,
                borderRadius: CARD_RADIUS,
                overflow: "hidden",
                // pink gradient placeholder — visible early before photos resolve
                background:
                  "linear-gradient(140deg, #F2D2CB 0%, #E8B5AC 45%, #D88B83 100%)",
                opacity: placeholderIn,
                boxShadow:
                  "0 18px 36px rgba(40,20,15,0.05), 0 4px 10px rgba(40,20,15,0.04)",
              }}
            >
              <Img
                src={staticFile(slot.src)}
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                  display: "block",
                  opacity: photoIn,
                }}
              />
              {/* tiny squiggle watermark in upper-right of each card (matches source) */}
              <div
                style={{
                  position: "absolute",
                  top: 14,
                  right: 16,
                  opacity: photoIn * 0.78,
                  filter: "drop-shadow(0 1px 2px rgba(0,0,0,0.25))",
                }}
              >
                <HiggsfieldMark size={18} color="#ffffff" />
              </div>
            </div>
          );
        })}
      </div>

      {/* ─────────── White wash over grid before Phase B ─────────── */}
      <AbsoluteFill
        style={{background: "#FFFFFF", opacity: gridWash, pointerEvents: "none"}}
      />

      {/* ─────────── Title block — right of grid ─────────── */}
      <div
        style={{
          position: "absolute",
          left: TITLE_X,
          top: TITLE_Y,
          opacity: titleDim,
          width: W - TITLE_X - 40,
        }}
      >
        <div
          style={{
            fontFamily: "Georgia, 'Times New Roman', serif",
            fontSize: TITLE_SIZE,
            fontWeight: 500,
            color: INK,
            letterSpacing: -1.6,
            lineHeight: 1.05,
          }}
        >
          {titleText.slice(0, titleVisibleChars)}
          <span style={{opacity: titleDots}}>...</span>
        </div>
        <div
          style={{
            marginTop: 24,
            fontFamily: "Georgia, 'Times New Roman', serif",
            fontSize: SUBLINE_SIZE,
            fontWeight: 400,
            color: SUBLINE,
            letterSpacing: -0.3,
            opacity: sublineVis,
            lineHeight: 1.1,
          }}
        >
          Detecting winning patterns
        </div>
      </div>

      {/* ─────────── Phase B: Input bar ─────────── */}
      <div
        style={{
          position: "absolute",
          left: BAR_X,
          top: BAR_Y + barRise + barDrift,
          width: BAR_W,
          height: BAR_H,
          borderRadius: BAR_RADIUS,
          background: "#FFFFFF",
          boxShadow:
            "0 32px 90px rgba(30,20,10,0.10), 0 8px 24px rgba(30,20,10,0.06)",
          opacity: barOpacity,
        }}
      >
        {/* Typed text — top-left of the bar, x=135-68=67 inside, y=460-365=95.
            The source shows TWO colors: ink-black for typed chars plus a faint
            peach 'autocomplete suggestion' for the remainder (visible early). */}
        <div
          style={{
            position: "absolute",
            left: 67,
            top: 95,
            fontSize: 50,
            fontWeight: 500,
            letterSpacing: -0.8,
            lineHeight: 1,
            display: "flex",
            alignItems: "baseline",
            whiteSpace: "pre",
          }}
        >
          <span style={{color: INK}}>{typedText}</span>
          <span
            style={{
              display: "inline-block",
              width: 3,
              height: 44,
              background: INK,
              marginLeft: 4,
              marginRight: 4,
              opacity: caretBlink,
              transform: "translateY(8px)",
            }}
          />
          <span style={{color: "#D8A89E", opacity: 0.85}}>
            {/* Faint peach suggestion: only show when typing in progress */}
            {visibleChars < charsTotal ? PROMPT_TEXT.slice(visibleChars) : ""}
          </span>
        </div>

        {/* '+' icon — bottom-left inside the bar.
            x_abs=135 -> 135-68=67, y_abs=600 -> 600-365=235 (center). */}
        <div
          style={{
            position: "absolute",
            left: 67 - PLUS_SIZE / 2 + 12,
            top: 235 - PLUS_SIZE / 2,
          }}
        >
          <PlusIcon size={PLUS_SIZE} color="#1A1A1A" />
        </div>

        {/* "Opus 4.7 v" — Gemini x=1450, y=585 (baseline).
            relative: x=1450-68=1382, y=585-365=220 */}
        <div
          style={{
            position: "absolute",
            left: 1382,
            top: 220 - 28,
            display: "flex",
            alignItems: "center",
            gap: 12,
            fontSize: 30,
            fontWeight: 500,
            color: INK,
            letterSpacing: -0.6,
          }}
        >
          <span>Opus 4.7</span>
          <ChevronDown size={22} color={INK} />
        </div>

        {/* Red send button — Gemini x=1725 y=560, 80x80, ~15px radius.
            relative: x=1725-68=1657, y=560-365=195 */}
        <div
          style={{
            position: "absolute",
            left: 1657,
            top: 195,
            width: SEND_BTN,
            height: SEND_BTN,
            borderRadius: SEND_RADIUS,
            background: BURNT,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            transform: `scale(${btnScale})`,
            boxShadow: "0 6px 14px rgba(192,83,59,0.30)",
          }}
        >
          <SendArrow size={34} />
        </div>
      </div>

      {/* ─────────── Hand-pointer cursor ─────────── */}
      <div
        style={{
          position: "absolute",
          left: handX,
          top: handY,
          opacity: handOpacity,
          pointerEvents: "none",
        }}
      >
        <HandCursor size={68} />
      </div>

      {/* ─────────── Phase C: wash to off-white ─────────── */}
      <AbsoluteFill
        style={{background: PAPER, opacity: wash, pointerEvents: "none"}}
      />

      {/* ─────────── Phase D: Higgsfield MCP logo ─────────── */}
      <AbsoluteFill
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          opacity: logoOpacity,
          pointerEvents: "none",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 18,
            transform: `scale(${logoScale})`,
          }}
        >
          <HiggsfieldMark size={68} color={HF_GREY} />
          <div
            style={{
              fontFamily: FONT_FAMILY,
              fontSize: 88,
              fontWeight: 600,
              color: HF_GREY,
              letterSpacing: -2.4,
              lineHeight: 1,
              display: "flex",
              alignItems: "flex-start",
              gap: 10,
            }}
          >
            <span>Higgsfield</span>
            <span
              style={{
                fontSize: 28,
                color: HF_MCP,
                fontWeight: 500,
                letterSpacing: -0.4,
                marginTop: 4,
              }}
            >
              MCP
            </span>
          </div>
        </div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};
