// =============================================================================
//  Scene 01 — seg000 (Remotion frames 0..181 @ 30fps; source @ 25fps)
//
//  Narrative beats (source frame → Remotion frame ≈ 3·(N−1)):
//   - 0..18    : "Claude Cowork" hero title + empty input pill fade IN
//                (paperclip cursor at bottom-left edge of input).
//   - 18..30   : hero+input fade OUT to clear the stage.
//   - 30..48   : empty "Connectors" card fades IN, centered.
//   - 48..62   : Higgsfield row enters from below; toggle still OFF (amber).
//   - 62..72   : Higgsfield toggle FLIPS to ON (amber → lime green, thumb
//                slides right with a snappy spring).
//   - 72..86   : Meta MCP row enters from below; toggle starts OFF (red).
//   - 86..96   : Meta MCP toggle FLIPS to ON (red → lime green).
//   - 96..108  : panel holds (both toggles green, both icons visible).
//   - 108..118 : Connectors card fades / scales OUT, empty input pill returns.
//   - 118..128 : Pink Früns pouch enters from off-canvas top-left with
//                directional motion blur, settles into top-left of input area,
//                tiny scale bounce on impact. Cursor morphs: pointer → grab.
//   - 128..170 : Variable-rate typewriter reveals the long multi-line prompt.
//   - 170..182 : Settled state, send button has a soft pulse.
//
//  Everything except the pink pouch is CSS/SVG — no other generated imagery.
//  The pouch is served from /aigen/scene01/fruns_pouch.png (generated by
//  scripts/gen_scene01.py). A CSS fallback paints if the asset is missing.
// =============================================================================

import React from "react";
import {AbsoluteFill, Img, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from "remotion";
import {FONT_FAMILY, bezier, clamped} from "../helpers";
import {MOTION, PALETTE} from "../tokens";

// -----------------------------------------------------------------------------
//  Local palette extension (Scene 01 only — additive, no token changes)
// -----------------------------------------------------------------------------
const C = {
  paper: PALETTE.paper, // #f4f0e8 warm off-white
  ink: "#0a0a0a",
  inkSoft: "#1a1a1a",
  coral: "#c5523a", // Anthropic/Claude coral starburst + send button
  coralBright: "#cc5a40",
  toggleOffAmber: "#b8860b",
  toggleOffAmberSoft: "#c89531",
  toggleOffRed: "#dc2626",
  // Slightly less saturated lime — matches the more muted source green
  toggleOnGreen: "#5fc828",
  toggleOnGreenSoft: "#82d44a",
  higgsLime: "#d6f650",
  metaBlue: "#1877f2",
  cardShadow: "0 1px 2px rgba(0,0,0,0.04), 0 8px 24px rgba(20,20,30,0.06)",
  pillShadow: "0 1px 2px rgba(0,0,0,0.03), 0 10px 28px rgba(20,20,30,0.07)",
};

const FONT_SERIF = "'Georgia', 'Times New Roman', serif";

const PROMPT_TEXT =
  "My brand is Früns — superfood gummies. Find the best ads my competitors are running in meta ads library, study my winning campaigns through meta ads mcp, and generate 20 videos based on what's working for me and my competitors.";

// -----------------------------------------------------------------------------
//  Helper: linear interpolation clamped between two frames (sugar)
// -----------------------------------------------------------------------------
const ramp = (frame: number, a: number, b: number, from = 0, to = 1) =>
  interpolate(frame, [a, b], [from, to], clamped);

// -----------------------------------------------------------------------------
//  Variable-rate typewriter — pauses on punctuation, slight burst on words.
// -----------------------------------------------------------------------------
const computeTypedChars = (typingProgress: number, text: string): number => {
  // typingProgress in [0..1] is a non-linear ease applied below.
  // We want micro-pauses on commas/periods. Build a cumulative weight per char
  // then map progress through that weight to get an integer cursor index.
  if (typingProgress <= 0) return 0;
  if (typingProgress >= 1) return text.length;
  const weights: number[] = [];
  let total = 0;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    let w = 1;
    if (ch === " ") w = 0.55;
    if (ch === "," || ch === ".") w = 5;
    if (ch === "—") w = 4;
    weights.push(w);
    total += w;
  }
  let target = typingProgress * total;
  let acc = 0;
  for (let i = 0; i < weights.length; i++) {
    acc += weights[i];
    if (acc >= target) return i + 1;
  }
  return text.length;
};

// -----------------------------------------------------------------------------
//  Sub-component: Claude starburst logo (12-spoke spark) as inline SVG.
// -----------------------------------------------------------------------------
const Starburst: React.FC<{size: number; color?: string}> = ({size, color = C.coral}) => {
  const spokes = 12;
  const cx = size / 2;
  const cy = size / 2;
  const outer = size * 0.46;
  const inner = size * 0.08;
  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} style={{display: "block"}}>
      {Array.from({length: spokes}).map((_, i) => {
        const angle = (i / spokes) * Math.PI * 2;
        const x1 = cx + Math.cos(angle) * inner;
        const y1 = cy + Math.sin(angle) * inner;
        const x2 = cx + Math.cos(angle) * outer;
        const y2 = cy + Math.sin(angle) * outer;
        return (
          <line
            key={i}
            x1={x1}
            y1={y1}
            x2={x2}
            y2={y2}
            stroke={color}
            strokeWidth={size * 0.075}
            strokeLinecap="round"
          />
        );
      })}
    </svg>
  );
};

// -----------------------------------------------------------------------------
//  Sub-component: Toggle switch with animated thumb + color crossfade.
//  state ∈ [0..1] : 0 = OFF, 1 = ON.
// -----------------------------------------------------------------------------
const ToggleSwitch: React.FC<{
  state: number;
  offColor: string;
  onColor: string;
  width?: number;
  height?: number;
}> = ({state, offColor, onColor, width = 96, height = 50}) => {
  // Background lerp between off and on colors.
  // Simple channel-wise lerp for compatible hex inputs.
  const hexToRgb = (h: string) => {
    const v = h.replace("#", "");
    return [parseInt(v.slice(0, 2), 16), parseInt(v.slice(2, 4), 16), parseInt(v.slice(4, 6), 16)];
  };
  const [r1, g1, b1] = hexToRgb(offColor);
  const [r2, g2, b2] = hexToRgb(onColor);
  const r = Math.round(r1 + (r2 - r1) * state);
  const g = Math.round(g1 + (g2 - g1) * state);
  const b = Math.round(b1 + (b2 - b1) * state);
  const thumbSize = height - 8;
  const thumbX = 4 + state * (width - thumbSize - 8);
  return (
    <div
      style={{
        width,
        height,
        borderRadius: height / 2,
        background: `rgb(${r}, ${g}, ${b})`,
        position: "relative",
        boxShadow: "inset 0 1px 2px rgba(0,0,0,0.12)",
        transition: "none",
      }}
    >
      <div
        style={{
          position: "absolute",
          top: 4,
          left: thumbX,
          width: thumbSize,
          height: thumbSize,
          borderRadius: "50%",
          background: "#ffffff",
          boxShadow: "0 2px 4px rgba(0,0,0,0.18), 0 0 1px rgba(0,0,0,0.1)",
        }}
      />
    </div>
  );
};

// -----------------------------------------------------------------------------
//  Sub-component: Higgsfield connector icon (lime square w/ black squiggle).
// -----------------------------------------------------------------------------
const HiggsIcon: React.FC<{size: number}> = ({size}) => (
  <div
    style={{
      width: size,
      height: size,
      borderRadius: size * 0.22,
      background: C.higgsLime,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    }}
  >
    <svg width={size * 0.7} height={size * 0.7} viewBox="0 0 100 100" style={{display: "block"}}>
      {/* squiggle: an S-curve sine-ish path */}
      <path
        d="M15 50 C 15 30, 35 30, 35 50 S 55 70, 55 50 S 75 30, 75 50 S 95 70, 95 50"
        fill="none"
        stroke="#0a0a0a"
        strokeWidth={9}
        strokeLinecap="round"
      />
    </svg>
  </div>
);

// -----------------------------------------------------------------------------
//  Sub-component: Meta/Facebook MCP icon (blue circle, white 'f').
// -----------------------------------------------------------------------------
const MetaIcon: React.FC<{size: number}> = ({size}) => (
  <div
    style={{
      width: size,
      height: size,
      borderRadius: "50%",
      background: C.metaBlue,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: "#ffffff",
      fontFamily: FONT_FAMILY,
      fontWeight: 900,
      fontSize: size * 0.74,
      lineHeight: 1,
      flexShrink: 0,
    }}
  >
    <span style={{transform: "translateY(2px) translateX(-1px)", fontStyle: "italic", fontFamily: FONT_SERIF}}>f</span>
  </div>
);

// -----------------------------------------------------------------------------
//  Sub-component: Pointer/Grab cursor (line-art hand). morph ∈ [0..1].
// -----------------------------------------------------------------------------
const HandCursor: React.FC<{morph: number; size?: number}> = ({morph, size = 72}) => {
  // 0 = open paperclip-pointer (fingers extended), 1 = grab (closed fist).
  // We draw two SVGs and crossfade.
  return (
    <div style={{width: size, height: size, position: "relative"}}>
      <svg
        width={size}
        height={size}
        viewBox="0 0 100 100"
        style={{position: "absolute", inset: 0, opacity: 1 - morph}}
      >
        {/* pointer hand — single finger up */}
        <path
          d="M40 88 L40 50 C40 45 47 45 47 50 L47 35 C47 30 54 30 54 35 L54 50 L54 38 C54 33 61 33 61 38 L61 52 L61 44 C61 39 68 39 68 44 L68 70 C68 80 60 88 50 88 Z"
          fill="#ffffff"
          stroke="#9a9a9a"
          strokeWidth={3}
          strokeLinejoin="round"
        />
      </svg>
      <svg
        width={size}
        height={size}
        viewBox="0 0 100 100"
        style={{position: "absolute", inset: 0, opacity: morph}}
      >
        {/* grab — closed fist */}
        <path
          d="M30 60 C30 48 38 42 50 42 L66 42 C76 42 80 50 80 56 L80 72 C80 82 72 90 62 90 L46 90 C36 90 30 82 30 72 Z"
          fill="#ffffff"
          stroke="#9a9a9a"
          strokeWidth={3}
          strokeLinejoin="round"
        />
        {/* knuckle ridges */}
        <path d="M40 50 L72 50 M40 60 L72 60 M40 70 L72 70" stroke="#bdbdbd" strokeWidth={2} fill="none" />
      </svg>
    </div>
  );
};

// -----------------------------------------------------------------------------
//  Sub-component: Früns pouch (uses generated image w/ CSS fallback).
//  The generated image is square 1024x1024 with white background and pouch
//  centered. We render with objectFit "contain" so the pouch shape reads true,
//  on a transparent (well, container is transparent) backdrop so it blends
//  cleanly into the white input pill.
// -----------------------------------------------------------------------------
const FrunsPouch: React.FC<{width: number; height: number}> = ({width, height}) => {
  const src = staticFile("aigen/scene01/fruns_pouch.png");
  return (
    <div
      style={{
        width,
        height,
        position: "relative",
        // No background, no border-radius — the pouch should read as a
        // free-floating product photo on the white input pill.
        overflow: "visible",
      }}
    >
      <Img
        src={src}
        style={{
          width: "100%",
          height: "100%",
          objectFit: "contain",
          display: "block",
        }}
        onError={() => undefined}
      />
    </div>
  );
};

// -----------------------------------------------------------------------------
//  Main scene
// -----------------------------------------------------------------------------
export const Scene01Seg000: React.FC = () => {
  const frame = useCurrentFrame();
  const {fps} = useVideoConfig();

  // ---- Beat 1: hero "Claude Cowork" + empty input pill (0..24) ------------
  // Source: hero+input fully visible from f001, fading by f008..f009, gone by f010.
  // Remotion: in 0..6 (short fast), hold, out 16..26.
  // We use a delay offset on the spring so by frame 0 we're already partway in.
  const heroIn = spring({frame: frame - 0 + 6, fps, config: MOTION.heroSpring, durationInFrames: 12});
  const heroOut = ramp(frame, 16, 26, 0, 1); // 0 = visible, 1 = gone
  const heroOpacity = Math.min(heroIn, 1) * (1 - heroOut);
  const heroY = (1 - heroIn) * 14;
  const heroScale = interpolate(heroIn, [0, 1], [0.985, 1]);

  // The empty input pill (Beat 1) shares the same in/out window.
  const inputAOpacity = Math.min(heroIn, 1) * (1 - heroOut);
  const inputAY = (1 - heroIn) * 18;

  // ---- Beat 2: Connectors card (overlapping hero outro) ------------------
  // Card starts coming in BEFORE hero is fully gone for a smooth crossfade.
  // Source: empty Connectors card by f010 → Remotion ~27.
  // Higgsfield row appears by f012 → Remotion ~33, toggle ON by f018 → Remotion 51.
  // Meta MCP row appears f016 → Remotion 45 with RED toggle, ON by f020 → Remotion 57.
  // Source f028 (Rem 81): last full visible. f032 (Rem 93): content GONE,
  // empty input bar visible. So card content (text+rows) fades out 82..92,
  // while the white card shape persists/morphs into the input bar.
  const cardIn = spring({frame: frame - 22, fps, config: MOTION.heroSpring});
  const cardContentOut = ramp(frame, 82, 94, 0, 1);
  const cardOpacity = Math.min(cardIn, 1) * (1 - cardContentOut);
  const cardY = (1 - cardIn) * 26;
  const cardScale = interpolate(cardIn, [0, 1], [0.97, 1]);

  // Higgsfield row (30..) and toggle flip (40..48). Source f013 (Rem 36) row
  // visible w/ OFF toggle, f016 (Rem 45) toggle GREEN.
  const higgsIn = spring({frame: frame - 30, fps, config: MOTION.snappy, durationInFrames: 12});
  const higgsRowOpacity = Math.min(higgsIn, 1);
  const higgsRowY = (1 - higgsIn) * 14;
  const higgsToggle = spring({frame: frame - 40, fps, config: MOTION.snappy, durationInFrames: 10});

  // Meta MCP row (44..) and toggle flip (54..62). Source f016 (Rem 45) row
  // appears w/ RED toggle, f019 (Rem 54) toggle GREEN.
  const metaIn = spring({frame: frame - 44, fps, config: MOTION.snappy, durationInFrames: 12});
  const metaRowOpacity = Math.min(metaIn, 1);
  const metaRowY = (1 - metaIn) * 14;
  const metaToggle = spring({frame: frame - 54, fps, config: MOTION.snappy, durationInFrames: 10});

  // ---- Beat 3: input pill emerges (87..98) -------------------------------
  // Input B fades in as the connectors content fades out. Same white pill
  // visually — the card morphs into the input. Source f032 (Rem 93): input
  // visible empty, no pouch yet.
  const inputBIn = ramp(frame, 87, 98, 0, 1);
  const inputBOpacity = inputBIn;
  const inputBY = (1 - inputBIn) * 18;

  // ---- Beat 4: pouch drop (95..112) --------------------------------------
  // Source f035 (Rem 102): pouch mid-flight w/ motion blur + grab cursor.
  // Source f038 (Rem 111): pouch settled, cursor still showing grab.
  // Source f040 (Rem 117): typing starts, no cursor.
  const dropStart = 95;
  const dropEase = bezier(MOTION.expoOut);
  const dropRaw = interpolate(frame, [dropStart, dropStart + 16], [0, 1], clamped);
  const drop = dropEase(dropRaw);
  // Bounce: overshoot 1.06 then settle at 1.0
  const bounceProg = interpolate(frame, [dropStart + 16, dropStart + 22, dropStart + 28], [0, 1, 0], clamped);
  const pouchScale = drop > 0 ? 1 + bounceProg * 0.05 : 0;
  // Translate from upper-left (-380px X, -240px Y) to settled (0, 0)
  const pouchX = interpolate(drop, [0, 1], [-380, 0]);
  const pouchY = interpolate(drop, [0, 1], [-240, 0]);
  // Motion blur on the way in — heavier blur for stronger sense of speed.
  const pouchBlur = interpolate(frame, [dropStart, dropStart + 8, dropStart + 14, dropStart + 16], [24, 14, 2, 0], clamped);
  const pouchOpacity = ramp(frame, dropStart, dropStart + 4, 0, 1);

  // Cursor: paperclip → grab → release. Visible 90..118, morph 98..108,
  // outro 113..118. We want the cursor GONE before typing starts.
  const cursorIntro = ramp(frame, 90, 96, 0, 1);
  const cursorMorph = ramp(frame, 98, 108, 0, 1);
  const cursorOutro = ramp(frame, 113, 119, 0, 1);
  const cursorOpacity = cursorIntro * (1 - cursorOutro);
  // Cursor flies along with pouch: starts off-screen, ends slightly bottom-right of pouch.
  const cursorX = interpolate(drop, [0, 1], [-340, 64]);
  const cursorY = interpolate(drop, [0, 1], [-200, 110]);

  // ---- Beat 5: typewriter (116..160) -------------------------------------
  // Source pacing (Remotion frames in parens):
  //   f038 (111): pouch settled, no text yet
  //   f040 (117): ~5 chars
  //   f042 (123): ~20 chars
  //   f045 (132): ~75 chars
  //   f048 (141): ~140 chars
  //   f050 (147): ~180 chars
  //   f052 (153): ~270 chars
  //   f055 (162): full text settled (280 chars)
  // Roughly linear with a soft slow-start and late-burst. Total ~44 frames.
  const typeStart = 113;
  const typeEnd = 160;
  const typeRaw = interpolate(frame, [typeStart, typeEnd], [0, 1], clamped);
  // EaseIn but starting earlier — faster initial typing so f045 catches up
  // to source's "best ads" position.
  const typeProgress = bezier([0.35, 0.05, 0.55, 1])(typeRaw);
  const typedCount = computeTypedChars(typeProgress, PROMPT_TEXT);
  const visibleText = PROMPT_TEXT.slice(0, typedCount);

  // Caret blink (every ~14 frames, only while not yet finished or just after)
  const caretOn = (frame >= typeStart) && Math.floor(frame / 14) % 2 === 0;
  const caretOpacity = caretOn ? 1 : 0.0;

  // ---- Beat 6: send button pulse (164..182) ------------------------------
  const sendPulseProg = interpolate(frame, [164, 172, 182], [0, 1, 0], clamped);
  const sendScale = 1 + sendPulseProg * 0.08;

  // ---- Layout constants --------------------------------------------------
  const STAGE_WIDTH = 1280;
  const CARD_WIDTH = 920;
  const CARD_HEIGHT = 360;
  const INPUT_WIDTH_A = 1280; // initial empty input (Beat 1)
  const INPUT_HEIGHT_A = 220;
  const INPUT_WIDTH_B = 1450; // final input with text (Beat 3+); wider to fit prompt
  const INPUT_HEIGHT_B = 430;

  return (
    <AbsoluteFill
      style={{
        background: C.paper,
        fontFamily: FONT_FAMILY,
        color: C.ink,
        overflow: "hidden",
      }}
    >
      {/* ---------- Beat 1: Hero title (Claude Cowork) ---------- */}
      <div
        style={{
          position: "absolute",
          top: "30%",
          left: 0,
          right: 0,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          opacity: heroOpacity,
          transform: `translateY(${heroY}px) scale(${heroScale})`,
        }}
      >
        <Starburst size={84} />
        <div
          style={{
            fontFamily: FONT_SERIF,
            fontWeight: 500,
            fontSize: 108,
            color: C.ink,
            letterSpacing: -2,
            marginLeft: 22,
            lineHeight: 1,
          }}
        >
          Claude Cowork
        </div>
      </div>

      {/* ---------- Beat 1: Empty input pill (under hero) ---------- */}
      <div
        style={{
          position: "absolute",
          top: "53%",
          left: "50%",
          width: INPUT_WIDTH_A,
          height: INPUT_HEIGHT_A,
          marginLeft: -INPUT_WIDTH_A / 2,
          background: "#ffffff",
          borderRadius: 36,
          boxShadow: C.pillShadow,
          opacity: inputAOpacity,
          transform: `translateY(${inputAY}px)`,
        }}
      >
        {/* + icon bottom-left */}
        <div
          style={{
            position: "absolute",
            left: 30,
            bottom: 30,
            width: 36,
            height: 36,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            color: C.ink,
            fontSize: 36,
            fontWeight: 300,
            lineHeight: 1,
          }}
        >
          +
        </div>
        {/* Opus 4.7 + send */}
        <div
          style={{
            position: "absolute",
            right: 30,
            bottom: 26,
            display: "flex",
            alignItems: "center",
            gap: 18,
          }}
        >
          <div style={{fontSize: 28, color: C.ink, fontFamily: FONT_SERIF}}>
            Opus 4.7 <span style={{fontSize: 20, marginLeft: 4}}>⌄</span>
          </div>
          <div
            style={{
              width: 56,
              height: 56,
              borderRadius: 12,
              background: C.coral,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              color: "#ffffff",
              fontSize: 28,
              fontWeight: 700,
            }}
          >
            ↑
          </div>
        </div>
      </div>

      {/* paperclip cursor below the input (Beat 1 hint) */}
      <div
        style={{
          position: "absolute",
          left: "13%",
          top: "73%",
          opacity: inputAOpacity * (1 - cursorIntro),
        }}
      >
        <HandCursor morph={0} size={64} />
      </div>

      {/* ---------- Beat 2: Connectors card ---------- */}
      <div
        style={{
          position: "absolute",
          top: "50%",
          left: "50%",
          width: CARD_WIDTH,
          height: CARD_HEIGHT,
          marginLeft: -CARD_WIDTH / 2,
          marginTop: -CARD_HEIGHT / 2,
          background: "#ffffff",
          borderRadius: 28,
          padding: 36,
          boxShadow: C.cardShadow,
          opacity: cardOpacity,
          transform: `translateY(${cardY}px) scale(${cardScale})`,
          boxSizing: "border-box",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <div
          style={{
            fontFamily: FONT_SERIF,
            fontSize: 56,
            fontWeight: 500,
            color: C.ink,
            marginBottom: 36,
            lineHeight: 1,
          }}
        >
          Connectors
        </div>

        {/* Higgsfield row */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            paddingTop: 8,
            paddingBottom: 18,
            opacity: higgsRowOpacity,
            transform: `translateY(${higgsRowY}px)`,
          }}
        >
          <div style={{display: "flex", alignItems: "center", gap: 22}}>
            <HiggsIcon size={66} />
            <div style={{fontFamily: FONT_SERIF, fontSize: 44, color: C.ink}}>Higgsfield</div>
          </div>
          <ToggleSwitch
            state={higgsToggle}
            offColor={C.toggleOffAmber}
            onColor={C.toggleOnGreen}
            width={108}
            height={54}
          />
        </div>

        {/* Meta MCP row */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            paddingTop: 18,
            opacity: metaRowOpacity,
            transform: `translateY(${metaRowY}px)`,
          }}
        >
          <div style={{display: "flex", alignItems: "center", gap: 22}}>
            <MetaIcon size={66} />
            <div style={{fontFamily: FONT_SERIF, fontSize: 44, color: C.ink}}>Meta MCP</div>
          </div>
          <ToggleSwitch
            state={metaToggle}
            offColor={C.toggleOffRed}
            onColor={C.toggleOnGreen}
            width={108}
            height={54}
          />
        </div>
      </div>

      {/* ---------- Beat 3+: final input pill w/ pouch + typed prompt ---------- */}
      <div
        style={{
          position: "absolute",
          top: "50%",
          left: "50%",
          width: INPUT_WIDTH_B,
          height: INPUT_HEIGHT_B,
          marginLeft: -INPUT_WIDTH_B / 2,
          marginTop: -INPUT_HEIGHT_B / 2 + 24,
          background: "#ffffff",
          borderRadius: 32,
          boxShadow: C.pillShadow,
          opacity: inputBOpacity,
          transform: `translateY(${inputBY}px)`,
          padding: "40px 48px",
          boxSizing: "border-box",
        }}
      >
        {/* Pouch slot top-left — pouch is taller than wide (stand-up pouch) */}
        {pouchOpacity > 0 && (
          <div
            style={{
              position: "absolute",
              left: 36,
              top: 30,
              width: 130,
              height: 156,
              opacity: pouchOpacity,
              transform: `translate(${pouchX}px, ${pouchY}px) scale(${pouchScale})`,
              transformOrigin: "center center",
              filter: `blur(${pouchBlur}px)`,
            }}
          >
            <FrunsPouch width={130} height={156} />
          </div>
        )}

        {/* Typed prompt text — starts below the pouch, fills the rest */}
        <div
          style={{
            position: "absolute",
            left: 36,
            top: 200,
            right: 36,
            color: C.ink,
            fontFamily: FONT_FAMILY,
            fontSize: 30,
            fontWeight: 500,
            lineHeight: 1.35,
            letterSpacing: -0.2,
            whiteSpace: "pre-wrap",
            wordBreak: "normal",
          }}
        >
          {visibleText}
          <span
            style={{
              display: "inline-block",
              width: 3,
              height: 30,
              background: C.ink,
              verticalAlign: "text-bottom",
              marginLeft: 2,
              opacity: typedCount > 0 && typedCount < PROMPT_TEXT.length ? caretOpacity : 0,
            }}
          />
        </div>

        {/* + bottom-left */}
        <div
          style={{
            position: "absolute",
            left: 30,
            bottom: 30,
            width: 36,
            height: 36,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            color: C.ink,
            fontSize: 36,
            fontWeight: 300,
            lineHeight: 1,
          }}
        >
          +
        </div>
        {/* Opus 4.7 + send button */}
        <div
          style={{
            position: "absolute",
            right: 30,
            bottom: 26,
            display: "flex",
            alignItems: "center",
            gap: 18,
          }}
        >
          <div style={{fontSize: 28, color: C.ink, fontFamily: FONT_SERIF}}>
            Opus 4.7 <span style={{fontSize: 20, marginLeft: 4}}>⌄</span>
          </div>
          <div
            style={{
              width: 56,
              height: 56,
              borderRadius: 12,
              background: C.coral,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              color: "#ffffff",
              fontSize: 28,
              fontWeight: 700,
              transform: `scale(${sendScale})`,
              transformOrigin: "center",
            }}
          >
            ↑
          </div>
        </div>

        {/* Grab cursor during drop */}
        {cursorOpacity > 0 && (
          <div
            style={{
              position: "absolute",
              left: 48,
              top: 36,
              opacity: cursorOpacity,
              transform: `translate(${cursorX}px, ${cursorY}px)`,
              pointerEvents: "none",
            }}
          >
            <HandCursor morph={cursorMorph} size={72} />
          </div>
        )}
      </div>
    </AbsoluteFill>
  );
};
